### ISSUE TITLE
Critical bug in upgradeShop

### ISSUE THREAD

**Issue by Espantonius** [pronze/SBA#123]
#### Describe the bug
I reported this for discord but no one knew the problem.

I have been installing the addon with bedwars for several days and the "upgradeShop" store does not work correctly from a certain version.

To carry out these tests i have installed several versions of the plugin and servers to see where the error is.
I have verified that in version 1.1.6 of SBAHypixelify, the upgrade store works. On the other hand, since version 1.2.6 it no longer works correctly.

In the following screenshot you can see the stores in different versions (1.1.6, 1.2.6 and 1.3.6): https://prnt.sc/139ogli

There is something wrong and the "upgradeShop" store doesn't work correctly. 

#### Server and plugin version
Spigot versions tested: 1.9.4, 1.12.2, 1.15.2 and 1.16.5
BedWars versions tested: 0.2.14 and 0.2.15
SBAHypixelify vesions tested: 1.1.6, 1.2.6, 1.3.6, 1.3.9, 1.4.0 and 1.4.3

**Comment by pronze** [comment]
Fixed in the latest SBA, reopen the issue if not.
