### ISSUE TITLE
Players (Non-OP) are able to break the Floating Rotating Generators

### ISSUE THREAD

**Issue by itsmemac** [pronze/SBA#124]
Facing an issue with the non-op player able to break the Floating Rotating Generators
As soon as they break, they get the block and an armor stand

[Video Link](https://www.youtube.com/watch?v=YIjbGVyf-xw)

tried with complete uninstall with just arena folder and same issue
player able to break the invisible armor stand 

There is no errors in onsole when this event happens and other feature continues as always.

[Bedwars config](https://paste.gg/p/anonymous/474611f911974ba693b5862f9c780439)

[bwaconfig](https://paste.gg/p/anonymous/cf846b1e075241b6b73cea9a9b70ce3d)

**Server version** : Paper version git-Paper-652 (MC: 1.16.5)
**Bedwars Version** : 0.2.15
**SBA version** : 1.4.3

**Plugins in server**
BattleTraining, BedWars, Citizens, DeluxeMenus, DiceFurniture, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, FurnitureLib, HeadDatabase, HeadDisplays, HolographicDisplays, HolographicExtension, IPWhitelist, Images, LiteBans, LuckPerms, Maintenance, Multiverse-Core, MysqlEcoBridge, OldCombatMechanics, PlaceholderAPI, ProtectionLib, ProtocolLib, QuickShop, SBAHypixelify, ServerUtils, SpawnJoin, TAB, TAB-BukkitBridge, TitleManager, UltraCustomizer, Vault, VoidGenerator, VoidSpawn, WDLCompanion, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, eZProtector and spark

**Tried options**
- Only Bedwars and SBA plugin in server (Same issue)
- Complete reconfigure of plugin with arena files intact (Same issue)
- Complete reconfigure of plugin with new arena set (Same issue)

**Comment by pronze** [comment]
Fixed in the latest version
