### ISSUE TITLE
Spigot Plugin Not Updated

### ISSUE THREAD

**Issue by PikachuPlays** [pronze/SBA#134]
I make servers using Aternos because I don't have a lot of free money to spend on a server. Aternos does allow plugins but they have to be popular enough and from a trusted website. Spigot being one of them. The SBA Addon plugins latest update is from December 17th 2020. I use the software paper, which is just spigot upgraded.

Server and plugin version
Paper version: #777
BedWars version: 0.2.15

Skin Restorer
ScreamingBedWars
SBA for ScreamingBedWars
HoloGraphicDisplays
OldCombatMechanics

**Comment by DeepFriedYeti** [comment]
Same issue

**Comment by pronze** [comment]
Well, Wait for Aternos to get SBA 1.5.0
