### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by DejArthur** [pronze/SBA#135]
Hello, I am creating a server with friends and we wanted to put a bedwars mode, everything works well but some improvements did not suit us. I have searched in the upgradeShop.yml file and I would like to limit the sharpness improvement to 1 but I didn't find how to do it.
Thanks for your help.

**Comment by StarbuckBarista** [comment]
The config for the team upgrades should be in `shops/upgradeShop.yml`, if you need to see the actual config it is [here](https://github.com/pronze/SBA/blob/master/plugin/src/main/resources/shops/upgradeShop.yml).
