### ISSUE TITLE
player shop and team upgrades

### ISSUE THREAD

**Issue by Shubham489B** [pronze/SBA#136]
Hello sir,
I created a small server and added screaming bedwars and sba hypixely to it.
the problem comes while playing the game the shop items have their prefix and color codes shown on the items this confuse player about the item info and price.
I tried to remove the color codes of the items but then the shop didnt worked it said to ask in discord can you help.
-Shubham Bhavsar

**Comment by pronze** [comment]
Hey there, Sorry for the issue, you can try deleting the SBA folder inside the plugins directory and installing the latest build from here: https://ci.screamingsandals.org/job/SBAHypixelify/

Do note SBA is intended for only Spigot/Paper 1.9.4 and above
