### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by ZayanPlayz** [pronze/SBA#140]
<html>
<body>

[14:41:46] [Server thread/ERROR]: Could not pass event ShopTransactionEvent to SBAHypixelify v1.4.3
--
1470 | java.lang.NullPointerException: Name is null
1471 | at java.lang.Enum.valueOf(Enum.java:271) ~[?:?]
1472 | at org.bukkit.Sound.valueOf(Sound.java:13) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1473 | at org.screamingsandals.bedwars.utils.Sounds.playSound(Sounds.java:1052) ~[?:?]
1474 | at io.pronze.hypixelify.inventories.CustomShop.handleBuy(CustomShop.java:728) ~[?:?]
1475 | at io.pronze.hypixelify.inventories.CustomShop.onShopTransaction(CustomShop.java:357) ~[?:?]
1476 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor614.execute(Unknown Source) ~[?:?]
1477 | at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1478 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1479 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1480 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1481 | at org.screamingsandals.bedwars.lib.sgui.listeners.InventoryListener.onInventoryClick(InventoryListener.java:172) ~[?:?]
1482 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor529.execute(Unknown Source) ~[?:?]
1483 | at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1484 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1485 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1486 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1487 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2728) ~[?:?]
1488 | at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:50) ~[?:?]
1489 | at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[?:?]
1490 | at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
1491 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1492 | at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
1493 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
1494 | at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1340) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1495 | at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1496 | at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
1497 | at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1498 | at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1499 | at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
1500 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1395) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1501 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1502 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[minecraft_server.jar:git-Paper-"4e2f0be"]
1503 | at java.lang.Thread.run(Thread.java:831) [?:?]

</body>
</html>

**Comment by StarbuckBarista** [comment]
Based on your error logs, you're still running v1.4.3, which is highly outdated. SBA is now on v2.0.0 and can be downloaded [here](https://ci.screamingsandals.org/job/SBAHypixelify/).

**Comment by PikachuPlays** [comment]
I am getting this issue too! It happens in 1.16.5 regardless of Paper or Spigot. I think it has to do with the new version of screaming bedwars. As I was not getting this before it was released. If a patch could come out that would be amazing! I also tried changing sound values in the config, it made zero difference.

**Comment by pronze** [comment]
Try this build, it should work :)
https://ci.screamingsandals.org/job/SBAHypixelify/
