### ISSUE TITLE
Java 16 Update 

### ISSUE THREAD

**Issue by Aadi-mone** [pronze/SBA#153]
Your plugin called SBA Addon for Hypixelfy that works with java 11, you said: 

NOTE: A MINIMUM OF JAVA 11 IS REQUIRED TO RUN THIS PLUGIN.

But I have Java 16 why it doesn't work with it?

As Minecraft 1.17 Update as come many plugins work with Java 16, But this plugin requires just java 11 and I have installed java 16

So I can't downgrade to java 11.

My question here is: Why does your plugin working with java 11 can't work with Java 16 as it is the higher version of it?

Please See this image btw

![Bug](https://user-images.githubusercontent.com/87631878/126105051-1021cfbf-5173-4d50-9cd6-8d21e345a933.png)

Thanks & Regards,
Adarsh A

**Comment by Aadi-mone** [comment]
@pronze Please Give a reply, I Like this plugin so much!

Please help me!

**Comment by TacoBillGlenWaverly** [comment]
@Aadi-mone, It works fine with java 16, the website means that you need AT LEAST java 11.

**Comment by Aadi-mone** [comment]
@HaddenB  Oh Ok I was mistaken, Thanks. :)
