### ISSUE TITLE
Unable to start game in 1.17

### ISSUE THREAD

**Issue by Francesco99d** [pronze/SBA#157]
I'm using the latest version of bedwars and the experimental version of the addon, but when I try to enter the game (even with maps that before the update did not give problems) now throws me out of the server when you should start the game

I leave you the logs of the error messages: https://paste.ee/p/jxGOW

P.s. I'm using Purpur 1.17

**Comment by zlataovce** [comment]
snapshots are not supported

**Comment by Francesco99d** [comment]
Ok, but I had to use this version because currently the official one doesn't work with Screaming BedWars 0.2.19

(I don't know if anything has changed in the meantime)

**Comment by zlataovce** [comment]
downgrade to sbw 0.2.18, 0.2.19 added only 1.17.1 support, nothing to worry about if you use 1.17 or lower

**Comment by Francesco99d** [comment]
The problem is that in the meantime I updated the server to 1.17.1... If I try to insert the old version of the addon? Without changing sba I create problems?

**Comment by zlataovce** [comment]
sba doesn't work in 1.17.1 in any way

**Comment by Francesco99d** [comment]
Oh okk, thanks for the clarification.... Is there any word yet on when and if it will be updated for 1.17.1? (I know very well that being summer is a bit difficult). I wish you a good day and good work ;)

**Comment by zlataovce** [comment]
there is no ETA, other than soon :)

**Comment by Francesco99d** [comment]
Ok, thank you very much :)
