### ISSUE TITLE
Dragon EGG

### ISSUE THREAD

**Issue by Aadi-mone** [pronze/SBA#159]
In the UpgradesShop.yml

The Dragon egg is saying not Configured Now what to do to fix it?? 

Please help!

**Comment by zlataovce** [comment]
dragons are not implemented

**Comment by Aadi-mone** [comment]
I don't Understand.

**Comment by zlataovce** [comment]
dragons are not implemented in the plugin, there is no way to enable them, it is just a placeholder

**Comment by Aadi-mone** [comment]
Oh, Okay then

Thanks!
