### ISSUE TITLE
Major Problem!!

### ISSUE THREAD

**Issue by Aadi-mone** [pronze/SBA#185]
Whenever I use Sba and plays bedwars with just 2 players the entire server with 5Gb ram laggs and the TPS drops critically low 

and playing without SBA in the Screaming bedwars plugin only solves the problem!! 

please take it seriously!

**Comment by Aadi-mone** [comment]
@zlataovce what do you mean by timings and spark profile?? 
and @zlataovce add all features to Screaming bedwars so we don't get lagg.

More info:
My normal server tps is 20. when the game starts with the SBA plugin installed the tps reduces to 13.2 or sometimes 3.5
same game same players without SBA is not laggy and the server tps is perfect 20.
and this means there is a very high load carried by the plugin!!

**Comment by zlataovce** [comment]
you didn't provide any evidence that sba is causing the lag, please create [a timings report](https://www.spigotmc.org/wiki/how-to-take-a-timings-report/) or [a spark profile](https://spark.lucko.me/docs/Command-Usage#spark-profiler).

**Comment by zlataovce** [comment]
> add all features to Screaming bedwars so we don't get lagg
no.

**Comment by Aadi-mone** [comment]
> you didn't provide any evidence that SBA is causing the lag, please create [a timings report](https://www.spigotmc.org/wiki/how-to-take-a-timings-report/) or [a spark profile](https://spark.lucko.me/docs/Command-Usage#spark-profiler).

I don't know why but this happens when I install SBA 

Timings Report: https://timings.aikar.co/?id=651add27373e436e81368118849ef43c
Spark Report:
```
03:02:55 INFO]: [⚡] Generating server health report...
[03:02:55 INFO]: 
[03:02:55 INFO]: > TPS from last 5s, 10s, 1m, 5m, 15m:
[03:02:55 INFO]:     *20.0, *20.0, *20.0, *20.0, *20.0
[03:02:55 INFO]: 
[03:02:55 INFO]: > Tick durations (min/med/95%ile/max ms) from last 10s, 1m:
[03:02:55 INFO]:     9.7/16.4/53.5/103.9; 6.5/11.9/37.5/172.3
[03:02:55 INFO]: 
[03:02:55 INFO]: > CPU usage from last 10s, 1m, 15m:
[03:02:55 INFO]:     79%, 79%, 79%  (system)
[03:02:55 INFO]:     1%, 1%, 2%  (process)
[03:02:55 INFO]: 
[03:02:55 INFO]: > Memory usage:
[03:02:55 INFO]:     920.6 MB / 2.2 GB   (40%)
[03:02:55 INFO]:     [////////////////    |                   ]
[03:02:55 INFO]: 
[03:02:55 INFO]: > Disk usage:
[03:02:55 INFO]:     75.2 GB / 216.6 GB   (34%)
[03:02:55 INFO]:     [/////////////                           ]
[03:02:55 INFO]: 
```
here's all that you asked.

**Comment by Aadi-mone** [comment]
@zlataovce  I didn't get a reply

**Comment by DeathGOD7** [comment]
System is at high usage (or dying to run your server). Are you using pterodactyl? And know that 1.17 Minecraft version takes more resources than normal, so just giving it 2gb ram is not enough. Please upgrade your ram.

**Comment by Aadi-mone** [comment]
> And know that 1.17 Minecraft version takes more resources than normal.

I am using 1.16

**Comment by DeathGOD7** [comment]
You said :
> Whenever I use Sba and plays bedwars with just 2 players the entire server with 5Gb ram laggs

But the report says you have 2 gigs of ram.

**Comment by Aadi-mone** [comment]
> Please provide your startup flags also.

How do I provide it?

**Comment by DeathGOD7** [comment]
> > Please provide your startup flags also.
> 
> How do I provide it?

You are running in petrodactyl or self-hosted server?
And by the looks of your timings it says : 
![image](https://user-images.githubusercontent.com/36422471/132136562-249d118e-0a29-4a33-b64f-aab70814ecb7.png)

**Comment by Aadi-mone** [comment]
> You are running self-hosted server?
Yes?

> And by the looks of your timings it says :
> ![image](https://user-images.githubusercontent.com/36422471/132136562-249d118e-0a29-4a33-b64f-aab70814ecb7.png)

I don't understand anything by looking the timings report so, know what should I do other than ram upgrade?

**Comment by Aadi-mone** [comment]
Now what should I do?

**Comment by DeathGOD7** [comment]
> Now what should I do?

Update more resources for your server.

**Comment by Aadi-mone** [comment]
If you mean its a Ram Upgrade, let me explain,
1st problem is I am using Bungee as a hub and sub servers as paper for SBA to run.
and I don't need a upgrade because the TPS is perfect before SBA being installed, but If I install SBA the TPS reduces, in which you can think, What I am doubting that is SBA a resource hungry plugin? 
Anyway the plugin is Awesome because most of the features are in it.
Hope you'll understand.
and thanks for the quick support.

**Comment by Aadi-mone** [comment]
what abt all world in one server with multiverse.

**Comment by DeathGOD7** [comment]
> what abt all world in one server with multiverse.

You can try that (multiple arena per world with multiverse)...so the paper instance doesn't take resources for each one.

**Comment by Aadi-mone** [comment]
**Yeah, that's a nice idea and works, but first of all answer this question why is only this happening when SBA has been installed?
I am now using bungee because of the lag, and even with it I am getting 12.3 TPS for just one map, Now imagine with SBA installed and 18 maps in one server with 3gigs.

@pronze  I don't know what is coding, but I gave this plugin to one developer to test the code, and he said this plugin is not optimized properly, and he said: Unoptimized Plugin = Unoptimized Server
he said something inside the code there is one task or something which is causing the lag.
I didn't say you or your plugins are bad, just to resolve this issue we tried many ways but we failed that's why I am here :/ 
and thanks for the help @DeathGOD7**

**Comment by DeathGOD7** [comment]
> Now imagine with SBA installed and 18 maps in one server with 3gigs.
So after smashing all maps in one server, you basically get other resources like ram and processing power free, no?
So you can assign those free resources to the one which you will use as server for bedwars with "18 maps".

And by the way is SBA and SBW only installed when you were doing bungee proxy servers? I think the problem is that paper doesn't well under 2gb. So either have 4 gb for each paper instance if you were going proxy style (recommended for high player count server.) otherwise 1 server with all maps and like 6-8 gb is enough for you.

So from what I understand, you have multiple (around or approx. 18) 2 gb instance of paper server ?

**Comment by Aadi-mone** [comment]
**as** per your advice, I took two servers from Humble Server Hosting 
First Package is 3 servers:
(Main Server [Bungee] with 1GB 
2nd Server with 1map and SBA and Bedwars plugin installed and you said 4gigs min so I took the 8GB 6$/mon
3rd server same as second)
2nd package is with 4igigs of ram and with multiple maps on PapperMC
I tried both methods u said, but it doesn't rely on what you say.
mainly the PVP and shop lag-s other than that as you said all was smooth but you know the PVP and shop are the major things in bedwars.
btw Now, what will you say? Upgrade CPU? huh? 
and don't say I wasted my money, I reduced the ram and use the server as Factions and Survival for my Server.**

**Comment by DeathGOD7** [comment]
Well I have 1 server (6 map, 4 gb) connected to proxy, which has 20-25 plugins. * SBA and SBW and others some specific plugins.
And it has 19.98 - 20 TPS (source : spark profiler) and vanilla /tps shows 20 solid.

> btw Now, what will you say? Upgrade CPU? huh?
and don't say I wasted my money, I reduced the ram and use the server as Factions and Survival for my Server.

Humble Server Hosting? Buy from trusted and reliable hosts like Apex or Minehut or other big hosts. * PS : Don't spend on random host just because they offer you cheap prices. Or better host on your own spare pc.

And to be 100% on my saying, your profiler shows : "x / 2GB" of spark. So even if you do 1.16.5 on multiple paper instance like 2-4 server with 2 gb ram each, it will lag like hell and hence "TPS Loss". It is not recommended to have 2 gb per server. (min is 4 gb each). 

Learn hosting/server specs info and paper requirements for server before blabbing about plugin or to other people who just wants to help you.

**Comment by DeathGOD7** [comment]
![image](https://user-images.githubusercontent.com/36422471/132949788-8d963deb-c033-4df4-ae13-255012b08a08.png)

**Comment by zlataovce** [comment]
your main thread is exhausted, can't reproduce such issues on other similarly configured servers.

**Comment by Aadi-mone** [comment]
I am sad now. 
now, what shd I upgrade :(
IDK whatever, thanks for the help 
whatever I do even though I am getting low tps
is there any way with Spark to increase performance, IDK how to use the commands :/
and I didn't blab out any people who tried to help me, I am just in a hurry.
and I took the budget plan cuz I am on a budget :/
I am just a poor guy :/ 
thanks for the help anyway!! 
thanks again.

**Comment by Aadi-mone** [comment]
**I tried to use SBA 1.4.3 and this solved my problem
@pronze and now I am 100% sure that there is something that I can't understand but you can which is too heavy.**
